"""rename unit_number to address on users

Revision ID: 8e00e0f63c53
Revises: 
Create Date: 2026-03-14 22:20:53.485984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e00e0f63c53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=200), nullable=True))
    op.drop_column('users', 'unit_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unit_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
